name: deploy-to-digital-ocean-staging

on:
  push:
    branches:
      - 'develop'

jobs:
  docker:
    runs-on: ubuntu-latest
    # this is stage, but it was named develop on gh for some reason and can't be modified
    environment: develop
    steps:
      - uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_DATABASE_URL: ${{ secrets.DATABASE_URL }}
          envkey_NEXT_PUBLIC_WEBAPP_URL: ${{ secrets.NEXT_PUBLIC_WEBAPP_URL }}
          envkey_NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          envkey_CALENDSO_ENCRYPTION_KEY: ${{ secrets.CALENDSO_ENCRYPTION_KEY }}

          envkey_NODE_ENV: "production"
          envkey_NEXT_PUBLIC_LICENSE_CONSENT: "agree"
      - name: Build image
        run: docker compose build calcom
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_TOKEN }}
      - name: Registry login
        run: doctl registry login
      - name: Tag and push image to stage
        run: |
          docker tag docker_calcom registry.digitalocean.com/mento/docker_calcom:stage
          docker push registry.digitalocean.com/mento/docker_calcom:stage
